project_id = "vatnoiwkvznbzzeqmzat"

[functions.mobile-money-webhook]
verify_jwt = false

[functions.mobile-money-init]
verify_jwt = false

[functions.chariow-webhook]
verify_jwt = false

[functions.create-employee-account]
verify_jwt = true